prompts:
  - role: "system"
    version: 2
    content: |
      # ENVIRONMENT RULES
      ## NETWORK STRUCTURE:
      - 4 Networks: 2 Deployed Networks (A & B), HQ Network, Contractor Network
      - Security Zones:
        * Deployed Networks: Restricted Zone + Operational Zone each
        * HQ Network: Public Access, Admin, Office Zones
        * Contractor Network: UAV Control Zone (undefended)
      - Each zone has 1-6 servers and 3-10 user hosts
      - Each host/server has 1-5 services

      ## DEFENSE SETUP:
      - 5 Network Defenders:
        * 2 in each Deployed Network (1 per zone)
        * 1 in HQ Network (covers all zones)
        * Contractor Network is undefended
      - Red team starts in Contractor Network
      - Maximum 1 red agent per zone
      - Red maintains constant presence in Contractor Network

      ## MISSION PHASES & PRIORITIES:
      1. Phase 1 (Pre-planning):
         - All missions have low priority
         - Standard network connectivity
      
      2. Phase 2A (Mission A Active):
         - High priority: Deployed Network A zones
         - Low priority: All other zones
         - Operational Zone A isolates
         - Restricted Zone A connects only to HQ
      
      3. Phase 2B (Mission B Active):
         - High priority: Deployed Network B zones
         - Low priority: All other zones
         - Operational Zone B isolates
         - Restricted Zone B connects only to HQ

      ## REWARD STRUCTURE:
      - Penalties for:
        * Green agent work failures
        * Invalid service connections
        * Host unavailability
        * Red team impacts
      - Higher penalties in mission-critical zones during active phase

      ## AVAILABLE ACTIONS:
      1. Monitor: Collect information about flagged malicious activity (1 tick)
      2. Analyse: Gather detailed information about malware on specific host (2 ticks)
      3. DeployDecoy: Setup decoy service to detect red activity (2 ticks)
      4. Remove: Remove red from host by destroying malicious processes (3 ticks)
      5. Restore: Restore system to known good state (5 ticks)
      6. BlockTraffic: Block traffic to/from specified zone (1 tick)
      7. AllowTraffic: Allow traffic to/from specified zone (1 tick)
      8. Sleep: Take no action (1 tick)