prompts:
  - role: "system"
    version: 2
    content: |
      # COMMVECTOR FORMAT
      Consider the following commvector BLUE AGENT structure. They summarize the current status of 
      each network based on the observation of each BLUE AGENT.

      ## BLUE AGENT NETWORKS

      - BLUE AGENT 0: restricted_zone_a
      - BLUE AGENT 1: operational_zone_a
      - BLUE AGENT 2: restricted_zone_b
      - BLUE AGENT 3: operational_zone_b
      - BLUE AGENT 4: public_access_zone, admin_network, office_network

      ## MESSAGE STRUCTURE
      - Bit 0 (BLUE AGENT 0 status): Malicious action detected from BLUE AGENT 0 network (1) or not (0)
      - Bit 1 (BLUE AGENT 1 status): Malicious action detected from BLUE AGENT 1 network (1) or not (0)
      - Bit 2 (BLUE AGENT 2 status): Malicious action detected from BLUE AGENT 2 network (1) or not (0)
      - Bit 3 (BLUE AGENT 3 status): Malicious action detected from BLUE AGENT 3 network (1) or not (0)
      - Bit 4 (BLUE AGENT 4 status): Malicious action detected from BLUE AGENT 4 network (1) or not (0)
      - Bits 5-6 (Compromise level of current BLUE AGENT's network): 
        00 - No compromise
        01 - Netscan/Remote exploit detected
        10 - User-level compromise
        11 - Admin-level compromise
      - Bit 7: Waiting for action being executed (1) or not (0)

      ## EXAMPLES
      - Commvector BLUE AGENT 1 Message: [0, 0, 0, 0, 0, 0, 0, 1]
      - Commvector BLUE AGENT 2 Message: [0, 0, 1, 0, 0, 0, 0, 0]
      - Commvector BLUE AGENT 3 Message: [0, 0, 0, 0, 0, 0, 0, 1]
      - Commvector BLUE AGENT 4 Message: [0, 0, 0, 0, 1, 1, 0, 0] 